config/routes.rb
Rails.application.routes.draw do
  get 'rooms/show'
  get 'mensajes/new'
  resources :users do
  	collection {post :import}
  end
  root to: 'users#index'
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
	after_create_commit {MessageBroadcastJob.perform_later self}
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, :first_name, :last_name, presence: true
  validates :email, uniqueness: true


  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |user|
        csv << user.attributes.values_at(*column_names)
      end
    end
  end

  def self.import(file) 
    success = 0
    unsuccess = 0
  	CSV.foreach(file.path, headers: true, skip_blanks: true) do |row|
      @user =  User.new(row.to_hash) 
      if @user.save
        success += 1
       else
        unsuccess += 1
       end
  	end
     json =    {unsuccess: unsuccess, success: success}.to_json
     result =JSON.parse(json, object_class: OpenStruct)
    return result
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  require 'ostruct'
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new 
  end
    # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:message)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def show
  	@messages = Message.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    respond_to do |format|
      format.html
      format.csv {
        @message = Message.new(message: 'Export in progres')
        if @message.save 
          Resque.enqueue(ExportWorker, @message.id)
          send_data @users.to_csv
        end        
     }
    end
  end

  def import    
    @user = User.last
    result =  User.import(params[:file])
    if result.empty?
      redirect_to root_url,  flash:{ danger:  "Invalid CSV file format."}
    else
      Resque.enqueue(ImportWorker, params[:file].original_filename ,result.unsuccess, result.success)
      redirect_to root_url , flash:{ success:  "Successfully import."} 
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BackgroundJobs</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
  	<% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
    <% end %>
  	<%= yield %>
   </div>
  </body>
</html>

app/views/messages/_message.html.erb
<% cache message do %>
	<div class="message">
		<p><%= message.message %></p>
		<span class="label label-info pull-right"><%= message.created_at.strftime("Created at %m/%d/%Y %H:%M:%S") %></span>		
	</div>	
<% end %>

app/views/messages/new.html.erb
<h1>Mensajes#new</h1>
<p>Find me in app/views/mensajes/new.html.erb</p>

app/views/rooms/show.html.erb
<div class="row">
	<h1>Messages..</h1>
	<%= link_to  root_path, class: "btn btn-primary pull-right " do%>
		<i class="glyphicon glyphicon-home"> Go Home</i>
	<% end %> 
	<div class="col-md-12">
		<div id="messages">
			<%= render @messages %>
		</div>
	</div>
	<div class="col-md-4">	
		<form>
			<div class="form-group">
				<label for="messageInput">Add a custom message:</label>
				<input class="form-control" type="text" data-behavior="room_speaker" id="messageInput" placeholder="Type and press enter...">
			</div>
		</form>
	</div>
</div>	

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Users</h1>
  <%= link_to "Download CSV", users_path(format: "csv"), class: "btn btn-primary " %>
  <h4>Import data</h4>
  <%= form_tag import_users_path, multipart: true do %>
    <%=file_field_tag :file %>
    <%= submit_tag "Import CSV" , required: true%>
  <% end %>
  <%= link_to "Action Cable", rooms_show_path, class: "btn btn-danger " %> 

<table class="table table-striped">
  <thead>
    <tr>
      <th>Email</th>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>